# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'spark_metrics'
    static_configs:
    - targets: ['spark-exporter:9108']

  - job_name: 'airflow'
    static_configs:
    - targets: ['airflow-exporter:9112']
    
  - job_name: 'gcp_metrics'
    gcp_sd_configs:
      - project: '${PROJECT_ID}'
        port: 9090
        
  - job_name: 'dataproc'
    gcp_sd_configs:
      - project: '${PROJECT_ID}'
        port: 9103
        filter: 'metadata.service=dataproc'